name: test-project
version: 1.0.0
organization: com.github.tammo
scalaVersion: 3.4.0
aggregates: [ first ]
# TODO make project includes?
dependencies:
  - organization: io.get-coursier
    name: coursier_2.13
    version: 2.1.9
modules:
  - name: first
    directory: modules/first
    aggregates: [ second ]
  - name: second
    directory: modules/second
    includes: [ coursier ]