name: test-project
version: 1.0.0
organization: com.github.tammo
scalaVersion: 3.4.0
aggregates: [ test ]
dependencies:
  - organization: io.get-coursier
    name: coursier_2.13
    version: 2.1.9
modules:
  test:
    name: test
    # TODO extend from parent
    organization: com.github.tammo
    version: 1.0.0
    directory: test
    scalaVersion: 3.4.0